# Generated by Django 5.0.2 on 2024-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
